// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for HealthzDb.
const (
	Down    HealthzDb = "down"
	Skipped HealthzDb = "skipped"
	Up      HealthzDb = "up"
)

// Valid indicates whether the value is a known member of the HealthzDb enum.
func (e HealthzDb) Valid() bool {
	switch e {
	case Down:
		return true
	case Skipped:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// ApiInfo defines model for ApiInfo.
type ApiInfo struct {
	Docs []string `json:"docs"`

	// Name Example: golottery
	Name string `json:"name"`

	// Phase Example: M0
	Phase string `json:"phase"`

	// Stack Example: echo+gorm+postgresql
	Stack string `json:"stack"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: INTERNAL_ERROR
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"requestId,omitempty"`
}

// Healthz defines model for Healthz.
type Healthz struct {
	// Db Database status
	Db *HealthzDb `json:"db,omitempty"`
	Ok bool       `json:"ok"`

	// Service Example: golottery-api
	Service string    `json:"service"`
	Ts      time.Time `json:"ts"`
}

// HealthzDb Database status
type HealthzDb string

// PlatformLoginRequest defines model for PlatformLoginRequest.
type PlatformLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PlatformMe defines model for PlatformMe.
type PlatformMe struct {
	Username string `json:"username"`
}

// SessionToken defines model for SessionToken.
type SessionToken struct {
	ExpiresAt time.Time `json:"expires_at"`

	// Token Bearer token plaintext; returned only once
	Token string `json:"token"`
}

// PlatformLoginJSONRequestBody defines body for PlatformLogin for application/json ContentType.
type PlatformLoginJSONRequestBody = PlatformLoginRequest

// ChangePlatformPasswordJSONRequestBody defines body for ChangePlatformPassword for application/json ContentType.
type ChangePlatformPasswordJSONRequestBody = ChangePasswordRequest
