// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx echo.Context) error
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx echo.Context) error
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx echo.Context) error
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiInfo(ctx)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// GetOpenAPIJSON converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIJSON(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIJSON(ctx)
	return err
}

// GetOpenAPIYaml converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIYaml(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIYaml(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz, options.OperationMiddlewares["getHealthz"]...)
	router.GET(options.BaseURL+"/api", wrapper.GetApiInfo, options.OperationMiddlewares["getApiInfo"]...)
	router.GET(options.BaseURL+"/openapi.yaml", wrapper.GetOpenAPIYaml, options.OperationMiddlewares["getOpenAPIYaml"]...)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPIJSON, options.OperationMiddlewares["getOpenAPIJSON"]...)

}

type GetApiInfoRequestObject struct {
}

type GetApiInfoResponseObject interface {
	VisitGetApiInfoResponse(w http.ResponseWriter) error
}

type GetApiInfo200JSONResponse ApiInfo

func (response GetApiInfo200JSONResponse) VisitGetApiInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Healthz

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz500JSONResponse Error

func (response GetHealthz500JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse Healthz

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIJSONRequestObject struct {
}

type GetOpenAPIJSONResponseObject interface {
	VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error
}

type GetOpenAPIJSON200JSONResponse map[string]interface{}

func (response GetOpenAPIJSON200JSONResponse) VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIYamlRequestObject struct {
}

type GetOpenAPIYamlResponseObject interface {
	VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error
}

type GetOpenAPIYaml200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenAPIYaml200ApplicationyamlResponse) VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx context.Context, request GetApiInfoRequestObject) (GetApiInfoResponseObject, error)
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx context.Context, request GetOpenAPIJSONRequestObject) (GetOpenAPIJSONResponseObject, error)
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx context.Context, request GetOpenAPIYamlRequestObject) (GetOpenAPIYamlResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiInfo operation middleware
func (sh *strictHandler) GetApiInfo(ctx echo.Context) error {
	var request GetApiInfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiInfo(ctx.Request().Context(), request.(GetApiInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiInfoResponseObject); ok {
		return validResponse.VisitGetApiInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx echo.Context) error {
	var request GetHealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx.Request().Context(), request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		return validResponse.VisitGetHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIJSON operation middleware
func (sh *strictHandler) GetOpenAPIJSON(ctx echo.Context) error {
	var request GetOpenAPIJSONRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIJSON(ctx.Request().Context(), request.(GetOpenAPIJSONRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIJSON")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIJSONResponseObject); ok {
		return validResponse.VisitGetOpenAPIJSONResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIYaml operation middleware
func (sh *strictHandler) GetOpenAPIYaml(ctx echo.Context) error {
	var request GetOpenAPIYamlRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIYaml(ctx.Request().Context(), request.(GetOpenAPIYamlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIYaml")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIYamlResponseObject); ok {
		return validResponse.VisitGetOpenAPIYamlResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFVdb9s2FP0rxN0eWlSRlQbZBr15WLB5yBfS7aEYguGaurZZSyRLXnn1Av/34VJWHdsysmFbXyKGPPfj",
	"HF4eP4F2jXeWLEconyDqBTWYlmNvJnbmZOmD8xTYUDqonE5fw9SkBa89QQmRg7Fz2GT9BoaAa/nfYkMC",
	"pE/Y+FqO5q52zBTWkB2H+wXGA/xNMQSMjHq5DyS9cG/mLjRvvIs8DxQ/1sehmwwCfWxNoArK37r++rp9",
	"2qwj+vg52E0/kGapexWCC8fCaFcdtD25/eXq4XZ8/fvVw8PdwxCFhmLEOQ3KKC1S5Eklp7ata5xKVg4t",
	"vcQotbLLPkTiJ8KaF38O3O80/aWog/FsnIUSfkDGKUZSkZHbCBmQbRup1Pqk1B9WhFsa76mCx6P2MnDL",
	"ZxynztWEVvYjhZXRp8bjDL0Zkq2b1pkLDTKUUCHTGZuGjrEHwrgl7GqmPMfaSIzZjv6+DPcuGlkaO1d6",
	"QXp5ZqxCWylnz6JhUtu21fh+ol7dFCpqnM1cXb3OpZjhfXYCgwxWFGKXv8jP8yKp5ckK9RIu8iK/kOFE",
	"XiTSo7T/BHNi+cjNofQkYwI/EvfvVnhH72zsbvVtUXQzaplsikTva6NT7OhDdHb3/mX1daAZlPDVaGcQ",
	"o+40jvoSSal9hb7HaLTaCqxMh8ogtk2DYQ0lvNseNcRYIaPogvModxPXkamBRwkYLXbjeYppP8H/I9O+",
	"xADTnoiJqus1Wd3lf1i8s5mB0r9a+uRJM1VJaQqKOqjUv/iS5F1QVW8NrcUVms6k9u/82qzIUozpqXzG",
	"e3mfJ25/O/953/CpEbjzZMf3k5/f3d3+2zHAqkpvG+v7Z3a4Z7bPDWJfj20fKjWyT74/qpxuG7KsXgno",
	"9UvM19jUf4P5e4H9I+Z94p3bbkuWqveanSiHZnqS+PvxzfWLxAU0THz7Q0BB9g9d99pprFVFK6qdl0yQ",
	"QRtqKGHB7MvR6Pztt3mRF/l5eXn5zXewedz8NQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
