// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx echo.Context) error
	// OrganizationLogin Organization admin login
	// (POST /api/organization/login)
	OrganizationLogin(ctx echo.Context) error
	// OrganizationLogout Revoke the current console token
	// (POST /api/organization/logout)
	OrganizationLogout(ctx echo.Context) error
	// GetOrganizationMe Current admin and its organization
	// (GET /api/organization/me)
	GetOrganizationMe(ctx echo.Context) error
	// ChangeOrganizationPassword Change the admin password
	// (POST /api/organization/password)
	ChangeOrganizationPassword(ctx echo.Context) error
	// PlatformLogin Platform operator login
	// (POST /api/platform/login)
	PlatformLogin(ctx echo.Context) error
	// PlatformLogout Revoke the current platform token
	// (POST /api/platform/logout)
	PlatformLogout(ctx echo.Context) error
	// GetPlatformMe Current platform operator
	// (GET /api/platform/me)
	GetPlatformMe(ctx echo.Context) error
	// ListOrgs List organizations, newest first
	// (GET /api/platform/orgs)
	ListOrgs(ctx echo.Context, params ListOrgsParams) error
	// CreateOrg Open an organization with its initial quota
	// (POST /api/platform/orgs)
	CreateOrg(ctx echo.Context) error
	// GetOrg Organization, quota and the latest 20 ledger entries
	// (GET /api/platform/orgs/{orgId})
	GetOrg(ctx echo.Context, orgId OrgId) error
	// AdjustOrgCredits Add or remove event credits with a reason
	// (POST /api/platform/orgs/{orgId}/credits)
	AdjustOrgCredits(ctx echo.Context, orgId OrgId) error
	// DisableOrg Disable an organization; idempotent
	// (POST /api/platform/orgs/{orgId}/disable)
	DisableOrg(ctx echo.Context, orgId OrgId) error
	// EnableOrg Enable an organization; idempotent
	// (POST /api/platform/orgs/{orgId}/enable)
	EnableOrg(ctx echo.Context, orgId OrgId) error
	// SetOrgMaxAttendees Change the default attendee limit for events created afterwards
	// (POST /api/platform/orgs/{orgId}/max-attendees)
	SetOrgMaxAttendees(ctx echo.Context, orgId OrgId) error
	// ListOrgUsers Admins of an organization
	// (GET /api/platform/orgs/{orgId}/users)
	ListOrgUsers(ctx echo.Context, orgId OrgId) error
	// CreateOrgUser Create an admin with a one-time password
	// (POST /api/platform/orgs/{orgId}/users)
	CreateOrgUser(ctx echo.Context, orgId OrgId) error
	// DisableOrgUser Disable an admin and revoke its tokens; idempotent
	// (POST /api/platform/orgs/{orgId}/users/{userId}/disable)
	DisableOrgUser(ctx echo.Context, orgId OrgId, userId UserId) error
	// EnableOrgUser Enable an admin without changing its password; idempotent
	// (POST /api/platform/orgs/{orgId}/users/{userId}/enable)
	EnableOrgUser(ctx echo.Context, orgId OrgId, userId UserId) error
	// ResetOrgUserPassword Replace the password and revoke every token of the admin
	// (POST /api/platform/orgs/{orgId}/users/{userId}/reset-password)
	ResetOrgUserPassword(ctx echo.Context, orgId OrgId, userId UserId) error
	// ChangePlatformPassword Change the platform operator password
	// (POST /api/platform/password)
	ChangePlatformPassword(ctx echo.Context) error
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx echo.Context) error
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx echo.Context) error
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiInfo(ctx)
	return err
}

// OrganizationLogin converts echo context to params.
func (w *ServerInterfaceWrapper) OrganizationLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OrganizationLogin(ctx)
	return err
}

// OrganizationLogout converts echo context to params.
func (w *ServerInterfaceWrapper) OrganizationLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OrganizationLogout(ctx)
	return err
}

// GetOrganizationMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMe(ctx)
	return err
}

// ChangeOrganizationPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangeOrganizationPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangeOrganizationPassword(ctx)
	return err
}

// PlatformLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PlatformLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlatformLogin(ctx)
	return err
}

// PlatformLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PlatformLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlatformLogout(ctx)
	return err
}

// GetPlatformMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlatformMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlatformMe(ctx)
	return err
}

// ListOrgs converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrgs(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrgsParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrgs(ctx, params)
	return err
}

// CreateOrg converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrg(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrg(ctx)
	return err
}

// GetOrg converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrg(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrg(ctx, orgId)
	return err
}

// AdjustOrgCredits converts echo context to params.
func (w *ServerInterfaceWrapper) AdjustOrgCredits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdjustOrgCredits(ctx, orgId)
	return err
}

// DisableOrg converts echo context to params.
func (w *ServerInterfaceWrapper) DisableOrg(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DisableOrg(ctx, orgId)
	return err
}

// EnableOrg converts echo context to params.
func (w *ServerInterfaceWrapper) EnableOrg(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnableOrg(ctx, orgId)
	return err
}

// SetOrgMaxAttendees converts echo context to params.
func (w *ServerInterfaceWrapper) SetOrgMaxAttendees(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetOrgMaxAttendees(ctx, orgId)
	return err
}

// ListOrgUsers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrgUsers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrgUsers(ctx, orgId)
	return err
}

// CreateOrgUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrgUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrgUser(ctx, orgId)
	return err
}

// DisableOrgUser converts echo context to params.
func (w *ServerInterfaceWrapper) DisableOrgUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DisableOrgUser(ctx, orgId, userId)
	return err
}

// EnableOrgUser converts echo context to params.
func (w *ServerInterfaceWrapper) EnableOrgUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnableOrgUser(ctx, orgId, userId)
	return err
}

// ResetOrgUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ResetOrgUserPassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "orgId" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", ctx.Param("orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter orgId: %s", err))
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResetOrgUserPassword(ctx, orgId, userId)
	return err
}

// ChangePlatformPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePlatformPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePlatformPassword(ctx)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// GetOpenAPIJSON converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIJSON(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIJSON(ctx)
	return err
}

// GetOpenAPIYaml converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIYaml(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIYaml(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz, options.OperationMiddlewares["getHealthz"]...)
	router.GET(options.BaseURL+"/api", wrapper.GetApiInfo, options.OperationMiddlewares["getApiInfo"]...)
	router.GET(options.BaseURL+"/openapi.yaml", wrapper.GetOpenAPIYaml, options.OperationMiddlewares["getOpenAPIYaml"]...)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPIJSON, options.OperationMiddlewares["getOpenAPIJSON"]...)
	router.POST(options.BaseURL+"/api/platform/login", wrapper.PlatformLogin, options.OperationMiddlewares["platformLogin"]...)
	router.POST(options.BaseURL+"/api/platform/logout", wrapper.PlatformLogout, options.OperationMiddlewares["platformLogout"]...)
	router.GET(options.BaseURL+"/api/platform/me", wrapper.GetPlatformMe, options.OperationMiddlewares["getPlatformMe"]...)
	router.POST(options.BaseURL+"/api/platform/password", wrapper.ChangePlatformPassword, options.OperationMiddlewares["changePlatformPassword"]...)
	router.GET(options.BaseURL+"/api/platform/orgs", wrapper.ListOrgs, options.OperationMiddlewares["listOrgs"]...)
	router.POST(options.BaseURL+"/api/platform/orgs", wrapper.CreateOrg, options.OperationMiddlewares["createOrg"]...)
	router.GET(options.BaseURL+"/api/platform/orgs/:orgId", wrapper.GetOrg, options.OperationMiddlewares["getOrg"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/disable", wrapper.DisableOrg, options.OperationMiddlewares["disableOrg"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/enable", wrapper.EnableOrg, options.OperationMiddlewares["enableOrg"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/credits", wrapper.AdjustOrgCredits, options.OperationMiddlewares["adjustOrgCredits"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/max-attendees", wrapper.SetOrgMaxAttendees, options.OperationMiddlewares["setOrgMaxAttendees"]...)
	router.GET(options.BaseURL+"/api/platform/orgs/:orgId/users", wrapper.ListOrgUsers, options.OperationMiddlewares["listOrgUsers"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/users", wrapper.CreateOrgUser, options.OperationMiddlewares["createOrgUser"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/users/:userId/reset-password", wrapper.ResetOrgUserPassword, options.OperationMiddlewares["resetOrgUserPassword"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/users/:userId/disable", wrapper.DisableOrgUser, options.OperationMiddlewares["disableOrgUser"]...)
	router.POST(options.BaseURL+"/api/platform/orgs/:orgId/users/:userId/enable", wrapper.EnableOrgUser, options.OperationMiddlewares["enableOrgUser"]...)
	router.POST(options.BaseURL+"/api/organization/login", wrapper.OrganizationLogin, options.OperationMiddlewares["organizationLogin"]...)
	router.POST(options.BaseURL+"/api/organization/logout", wrapper.OrganizationLogout, options.OperationMiddlewares["organizationLogout"]...)
	router.GET(options.BaseURL+"/api/organization/me", wrapper.GetOrganizationMe, options.OperationMiddlewares["getOrganizationMe"]...)
	router.POST(options.BaseURL+"/api/organization/password", wrapper.ChangeOrganizationPassword, options.OperationMiddlewares["changeOrganizationPassword"]...)

}

type ErrorJSONResponse Error

type GetApiInfoRequestObject struct {
}

type GetApiInfoResponseObject interface {
	VisitGetApiInfoResponse(w http.ResponseWriter) error
}

type GetApiInfo200JSONResponse ApiInfo

func (response GetApiInfo200JSONResponse) VisitGetApiInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizationLoginRequestObject struct {
	Body *OrganizationLoginJSONRequestBody
}

type OrganizationLoginResponseObject interface {
	VisitOrganizationLoginResponse(w http.ResponseWriter) error
}

type OrganizationLogin200JSONResponse OrganizationSession

func (response OrganizationLogin200JSONResponse) VisitOrganizationLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizationLogin401JSONResponse struct{ ErrorJSONResponse }

func (response OrganizationLogin401JSONResponse) VisitOrganizationLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizationLogin429JSONResponse Error

func (response OrganizationLogin429JSONResponse) VisitOrganizationLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizationLogoutRequestObject struct {
}

type OrganizationLogoutResponseObject interface {
	VisitOrganizationLogoutResponse(w http.ResponseWriter) error
}

type OrganizationLogout204Response struct {
}

func (response OrganizationLogout204Response) VisitOrganizationLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OrganizationLogout401JSONResponse struct{ ErrorJSONResponse }

func (response OrganizationLogout401JSONResponse) VisitOrganizationLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganizationMeRequestObject struct {
}

type GetOrganizationMeResponseObject interface {
	VisitGetOrganizationMeResponse(w http.ResponseWriter) error
}

type GetOrganizationMe200JSONResponse OrganizationMe

func (response GetOrganizationMe200JSONResponse) VisitGetOrganizationMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrganizationMe401JSONResponse struct{ ErrorJSONResponse }

func (response GetOrganizationMe401JSONResponse) VisitGetOrganizationMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeOrganizationPasswordRequestObject struct {
	Body *ChangeOrganizationPasswordJSONRequestBody
}

type ChangeOrganizationPasswordResponseObject interface {
	VisitChangeOrganizationPasswordResponse(w http.ResponseWriter) error
}

type ChangeOrganizationPassword200JSONResponse SessionToken

func (response ChangeOrganizationPassword200JSONResponse) VisitChangeOrganizationPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeOrganizationPassword400JSONResponse struct{ ErrorJSONResponse }

func (response ChangeOrganizationPassword400JSONResponse) VisitChangeOrganizationPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeOrganizationPassword401JSONResponse Error

func (response ChangeOrganizationPassword401JSONResponse) VisitChangeOrganizationPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLoginRequestObject struct {
	Body *PlatformLoginJSONRequestBody
}

type PlatformLoginResponseObject interface {
	VisitPlatformLoginResponse(w http.ResponseWriter) error
}

type PlatformLogin200JSONResponse SessionToken

func (response PlatformLogin200JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogin401JSONResponse struct{ ErrorJSONResponse }

func (response PlatformLogin401JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogin429JSONResponse Error

func (response PlatformLogin429JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogoutRequestObject struct {
}

type PlatformLogoutResponseObject interface {
	VisitPlatformLogoutResponse(w http.ResponseWriter) error
}

type PlatformLogout204Response struct {
}

func (response PlatformLogout204Response) VisitPlatformLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PlatformLogout401JSONResponse struct{ ErrorJSONResponse }

func (response PlatformLogout401JSONResponse) VisitPlatformLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlatformMeRequestObject struct {
}

type GetPlatformMeResponseObject interface {
	VisitGetPlatformMeResponse(w http.ResponseWriter) error
}

type GetPlatformMe200JSONResponse PlatformMe

func (response GetPlatformMe200JSONResponse) VisitGetPlatformMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlatformMe401JSONResponse struct{ ErrorJSONResponse }

func (response GetPlatformMe401JSONResponse) VisitGetPlatformMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgsRequestObject struct {
	Params ListOrgsParams
}

type ListOrgsResponseObject interface {
	VisitListOrgsResponse(w http.ResponseWriter) error
}

type ListOrgs200JSONResponse OrgPage

func (response ListOrgs200JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgs401JSONResponse struct{ ErrorJSONResponse }

func (response ListOrgs401JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgRequestObject struct {
	Body *CreateOrgJSONRequestBody
}

type CreateOrgResponseObject interface {
	VisitCreateOrgResponse(w http.ResponseWriter) error
}

type CreateOrg201JSONResponse OrgSummary

func (response CreateOrg201JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg400JSONResponse struct{ ErrorJSONResponse }

func (response CreateOrg400JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg401JSONResponse Error

func (response CreateOrg401JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrgRequestObject struct {
	OrgId OrgId `json:"orgId"`
}

type GetOrgResponseObject interface {
	VisitGetOrgResponse(w http.ResponseWriter) error
}

type GetOrg200JSONResponse OrgDetail

func (response GetOrg200JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg401JSONResponse struct{ ErrorJSONResponse }

func (response GetOrg401JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg404JSONResponse Error

func (response GetOrg404JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustOrgCreditsRequestObject struct {
	OrgId OrgId `json:"orgId"`
	Body  *AdjustOrgCreditsJSONRequestBody
}

type AdjustOrgCreditsResponseObject interface {
	VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error
}

type AdjustOrgCredits200JSONResponse LedgerEntry

func (response AdjustOrgCredits200JSONResponse) VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustOrgCredits400JSONResponse struct{ ErrorJSONResponse }

func (response AdjustOrgCredits400JSONResponse) VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustOrgCredits401JSONResponse Error

func (response AdjustOrgCredits401JSONResponse) VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustOrgCredits404JSONResponse Error

func (response AdjustOrgCredits404JSONResponse) VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustOrgCredits409JSONResponse Error

func (response AdjustOrgCredits409JSONResponse) VisitAdjustOrgCreditsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DisableOrgRequestObject struct {
	OrgId OrgId `json:"orgId"`
}

type DisableOrgResponseObject interface {
	VisitDisableOrgResponse(w http.ResponseWriter) error
}

type DisableOrg204Response struct {
}

func (response DisableOrg204Response) VisitDisableOrgResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DisableOrg401JSONResponse struct{ ErrorJSONResponse }

func (response DisableOrg401JSONResponse) VisitDisableOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DisableOrg404JSONResponse Error

func (response DisableOrg404JSONResponse) VisitDisableOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnableOrgRequestObject struct {
	OrgId OrgId `json:"orgId"`
}

type EnableOrgResponseObject interface {
	VisitEnableOrgResponse(w http.ResponseWriter) error
}

type EnableOrg204Response struct {
}

func (response EnableOrg204Response) VisitEnableOrgResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EnableOrg401JSONResponse struct{ ErrorJSONResponse }

func (response EnableOrg401JSONResponse) VisitEnableOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnableOrg404JSONResponse Error

func (response EnableOrg404JSONResponse) VisitEnableOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SetOrgMaxAttendeesRequestObject struct {
	OrgId OrgId `json:"orgId"`
	Body  *SetOrgMaxAttendeesJSONRequestBody
}

type SetOrgMaxAttendeesResponseObject interface {
	VisitSetOrgMaxAttendeesResponse(w http.ResponseWriter) error
}

type SetOrgMaxAttendees204Response struct {
}

func (response SetOrgMaxAttendees204Response) VisitSetOrgMaxAttendeesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetOrgMaxAttendees400JSONResponse struct{ ErrorJSONResponse }

func (response SetOrgMaxAttendees400JSONResponse) VisitSetOrgMaxAttendeesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetOrgMaxAttendees401JSONResponse Error

func (response SetOrgMaxAttendees401JSONResponse) VisitSetOrgMaxAttendeesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetOrgMaxAttendees404JSONResponse Error

func (response SetOrgMaxAttendees404JSONResponse) VisitSetOrgMaxAttendeesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgUsersRequestObject struct {
	OrgId OrgId `json:"orgId"`
}

type ListOrgUsersResponseObject interface {
	VisitListOrgUsersResponse(w http.ResponseWriter) error
}

type ListOrgUsers200JSONResponse []OrgUser

func (response ListOrgUsers200JSONResponse) VisitListOrgUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgUsers401JSONResponse struct{ ErrorJSONResponse }

func (response ListOrgUsers401JSONResponse) VisitListOrgUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgUsers404JSONResponse Error

func (response ListOrgUsers404JSONResponse) VisitListOrgUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgUserRequestObject struct {
	OrgId OrgId `json:"orgId"`
	Body  *CreateOrgUserJSONRequestBody
}

type CreateOrgUserResponseObject interface {
	VisitCreateOrgUserResponse(w http.ResponseWriter) error
}

type CreateOrgUser201JSONResponse OrgUserWithPassword

func (response CreateOrgUser201JSONResponse) VisitCreateOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgUser400JSONResponse struct{ ErrorJSONResponse }

func (response CreateOrgUser400JSONResponse) VisitCreateOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgUser401JSONResponse Error

func (response CreateOrgUser401JSONResponse) VisitCreateOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgUser404JSONResponse Error

func (response CreateOrgUser404JSONResponse) VisitCreateOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgUser409JSONResponse Error

func (response CreateOrgUser409JSONResponse) VisitCreateOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DisableOrgUserRequestObject struct {
	OrgId  OrgId  `json:"orgId"`
	UserId UserId `json:"userId"`
}

type DisableOrgUserResponseObject interface {
	VisitDisableOrgUserResponse(w http.ResponseWriter) error
}

type DisableOrgUser204Response struct {
}

func (response DisableOrgUser204Response) VisitDisableOrgUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DisableOrgUser401JSONResponse struct{ ErrorJSONResponse }

func (response DisableOrgUser401JSONResponse) VisitDisableOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DisableOrgUser404JSONResponse Error

func (response DisableOrgUser404JSONResponse) VisitDisableOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnableOrgUserRequestObject struct {
	OrgId  OrgId  `json:"orgId"`
	UserId UserId `json:"userId"`
}

type EnableOrgUserResponseObject interface {
	VisitEnableOrgUserResponse(w http.ResponseWriter) error
}

type EnableOrgUser204Response struct {
}

func (response EnableOrgUser204Response) VisitEnableOrgUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EnableOrgUser401JSONResponse struct{ ErrorJSONResponse }

func (response EnableOrgUser401JSONResponse) VisitEnableOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnableOrgUser404JSONResponse Error

func (response EnableOrgUser404JSONResponse) VisitEnableOrgUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResetOrgUserPasswordRequestObject struct {
	OrgId  OrgId  `json:"orgId"`
	UserId UserId `json:"userId"`
}

type ResetOrgUserPasswordResponseObject interface {
	VisitResetOrgUserPasswordResponse(w http.ResponseWriter) error
}

type ResetOrgUserPassword200JSONResponse OneTimePassword

func (response ResetOrgUserPassword200JSONResponse) VisitResetOrgUserPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResetOrgUserPassword401JSONResponse struct{ ErrorJSONResponse }

func (response ResetOrgUserPassword401JSONResponse) VisitResetOrgUserPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ResetOrgUserPassword404JSONResponse Error

func (response ResetOrgUserPassword404JSONResponse) VisitResetOrgUserPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPasswordRequestObject struct {
	Body *ChangePlatformPasswordJSONRequestBody
}

type ChangePlatformPasswordResponseObject interface {
	VisitChangePlatformPasswordResponse(w http.ResponseWriter) error
}

type ChangePlatformPassword200JSONResponse SessionToken

func (response ChangePlatformPassword200JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPassword400JSONResponse struct{ ErrorJSONResponse }

func (response ChangePlatformPassword400JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPassword401JSONResponse Error

func (response ChangePlatformPassword401JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Healthz

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz500JSONResponse Error

func (response GetHealthz500JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse Healthz

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIJSONRequestObject struct {
}

type GetOpenAPIJSONResponseObject interface {
	VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error
}

type GetOpenAPIJSON200JSONResponse map[string]interface{}

func (response GetOpenAPIJSON200JSONResponse) VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIYamlRequestObject struct {
}

type GetOpenAPIYamlResponseObject interface {
	VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error
}

type GetOpenAPIYaml200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenAPIYaml200ApplicationyamlResponse) VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx context.Context, request GetApiInfoRequestObject) (GetApiInfoResponseObject, error)
	// OrganizationLogin Organization admin login
	// (POST /api/organization/login)
	OrganizationLogin(ctx context.Context, request OrganizationLoginRequestObject) (OrganizationLoginResponseObject, error)
	// OrganizationLogout Revoke the current console token
	// (POST /api/organization/logout)
	OrganizationLogout(ctx context.Context, request OrganizationLogoutRequestObject) (OrganizationLogoutResponseObject, error)
	// GetOrganizationMe Current admin and its organization
	// (GET /api/organization/me)
	GetOrganizationMe(ctx context.Context, request GetOrganizationMeRequestObject) (GetOrganizationMeResponseObject, error)
	// ChangeOrganizationPassword Change the admin password
	// (POST /api/organization/password)
	ChangeOrganizationPassword(ctx context.Context, request ChangeOrganizationPasswordRequestObject) (ChangeOrganizationPasswordResponseObject, error)
	// PlatformLogin Platform operator login
	// (POST /api/platform/login)
	PlatformLogin(ctx context.Context, request PlatformLoginRequestObject) (PlatformLoginResponseObject, error)
	// PlatformLogout Revoke the current platform token
	// (POST /api/platform/logout)
	PlatformLogout(ctx context.Context, request PlatformLogoutRequestObject) (PlatformLogoutResponseObject, error)
	// GetPlatformMe Current platform operator
	// (GET /api/platform/me)
	GetPlatformMe(ctx context.Context, request GetPlatformMeRequestObject) (GetPlatformMeResponseObject, error)
	// ListOrgs List organizations, newest first
	// (GET /api/platform/orgs)
	ListOrgs(ctx context.Context, request ListOrgsRequestObject) (ListOrgsResponseObject, error)
	// CreateOrg Open an organization with its initial quota
	// (POST /api/platform/orgs)
	CreateOrg(ctx context.Context, request CreateOrgRequestObject) (CreateOrgResponseObject, error)
	// GetOrg Organization, quota and the latest 20 ledger entries
	// (GET /api/platform/orgs/{orgId})
	GetOrg(ctx context.Context, request GetOrgRequestObject) (GetOrgResponseObject, error)
	// AdjustOrgCredits Add or remove event credits with a reason
	// (POST /api/platform/orgs/{orgId}/credits)
	AdjustOrgCredits(ctx context.Context, request AdjustOrgCreditsRequestObject) (AdjustOrgCreditsResponseObject, error)
	// DisableOrg Disable an organization; idempotent
	// (POST /api/platform/orgs/{orgId}/disable)
	DisableOrg(ctx context.Context, request DisableOrgRequestObject) (DisableOrgResponseObject, error)
	// EnableOrg Enable an organization; idempotent
	// (POST /api/platform/orgs/{orgId}/enable)
	EnableOrg(ctx context.Context, request EnableOrgRequestObject) (EnableOrgResponseObject, error)
	// SetOrgMaxAttendees Change the default attendee limit for events created afterwards
	// (POST /api/platform/orgs/{orgId}/max-attendees)
	SetOrgMaxAttendees(ctx context.Context, request SetOrgMaxAttendeesRequestObject) (SetOrgMaxAttendeesResponseObject, error)
	// ListOrgUsers Admins of an organization
	// (GET /api/platform/orgs/{orgId}/users)
	ListOrgUsers(ctx context.Context, request ListOrgUsersRequestObject) (ListOrgUsersResponseObject, error)
	// CreateOrgUser Create an admin with a one-time password
	// (POST /api/platform/orgs/{orgId}/users)
	CreateOrgUser(ctx context.Context, request CreateOrgUserRequestObject) (CreateOrgUserResponseObject, error)
	// DisableOrgUser Disable an admin and revoke its tokens; idempotent
	// (POST /api/platform/orgs/{orgId}/users/{userId}/disable)
	DisableOrgUser(ctx context.Context, request DisableOrgUserRequestObject) (DisableOrgUserResponseObject, error)
	// EnableOrgUser Enable an admin without changing its password; idempotent
	// (POST /api/platform/orgs/{orgId}/users/{userId}/enable)
	EnableOrgUser(ctx context.Context, request EnableOrgUserRequestObject) (EnableOrgUserResponseObject, error)
	// ResetOrgUserPassword Replace the password and revoke every token of the admin
	// (POST /api/platform/orgs/{orgId}/users/{userId}/reset-password)
	ResetOrgUserPassword(ctx context.Context, request ResetOrgUserPasswordRequestObject) (ResetOrgUserPasswordResponseObject, error)
	// ChangePlatformPassword Change the platform operator password
	// (POST /api/platform/password)
	ChangePlatformPassword(ctx context.Context, request ChangePlatformPasswordRequestObject) (ChangePlatformPasswordResponseObject, error)
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx context.Context, request GetOpenAPIJSONRequestObject) (GetOpenAPIJSONResponseObject, error)
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx context.Context, request GetOpenAPIYamlRequestObject) (GetOpenAPIYamlResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiInfo operation middleware
func (sh *strictHandler) GetApiInfo(ctx echo.Context) error {
	var request GetApiInfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiInfo(ctx.Request().Context(), request.(GetApiInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiInfoResponseObject); ok {
		return validResponse.VisitGetApiInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OrganizationLogin operation middleware
func (sh *strictHandler) OrganizationLogin(ctx echo.Context) error {
	var request OrganizationLoginRequestObject

	var body OrganizationLoginJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizationLogin(ctx.Request().Context(), request.(OrganizationLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizationLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OrganizationLoginResponseObject); ok {
		return validResponse.VisitOrganizationLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OrganizationLogout operation middleware
func (sh *strictHandler) OrganizationLogout(ctx echo.Context) error {
	var request OrganizationLogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizationLogout(ctx.Request().Context(), request.(OrganizationLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizationLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OrganizationLogoutResponseObject); ok {
		return validResponse.VisitOrganizationLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOrganizationMe operation middleware
func (sh *strictHandler) GetOrganizationMe(ctx echo.Context) error {
	var request GetOrganizationMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganizationMe(ctx.Request().Context(), request.(GetOrganizationMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganizationMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOrganizationMeResponseObject); ok {
		return validResponse.VisitGetOrganizationMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangeOrganizationPassword operation middleware
func (sh *strictHandler) ChangeOrganizationPassword(ctx echo.Context) error {
	var request ChangeOrganizationPasswordRequestObject

	var body ChangeOrganizationPasswordJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangeOrganizationPassword(ctx.Request().Context(), request.(ChangeOrganizationPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangeOrganizationPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangeOrganizationPasswordResponseObject); ok {
		return validResponse.VisitChangeOrganizationPasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PlatformLogin operation middleware
func (sh *strictHandler) PlatformLogin(ctx echo.Context) error {
	var request PlatformLoginRequestObject

	var body PlatformLoginJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformLogin(ctx.Request().Context(), request.(PlatformLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PlatformLoginResponseObject); ok {
		return validResponse.VisitPlatformLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PlatformLogout operation middleware
func (sh *strictHandler) PlatformLogout(ctx echo.Context) error {
	var request PlatformLogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformLogout(ctx.Request().Context(), request.(PlatformLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PlatformLogoutResponseObject); ok {
		return validResponse.VisitPlatformLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPlatformMe operation middleware
func (sh *strictHandler) GetPlatformMe(ctx echo.Context) error {
	var request GetPlatformMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlatformMe(ctx.Request().Context(), request.(GetPlatformMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlatformMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPlatformMeResponseObject); ok {
		return validResponse.VisitGetPlatformMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListOrgs operation middleware
func (sh *strictHandler) ListOrgs(ctx echo.Context, params ListOrgsParams) error {
	var request ListOrgsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrgs(ctx.Request().Context(), request.(ListOrgsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrgs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListOrgsResponseObject); ok {
		return validResponse.VisitListOrgsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateOrg operation middleware
func (sh *strictHandler) CreateOrg(ctx echo.Context) error {
	var request CreateOrgRequestObject

	var body CreateOrgJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrg(ctx.Request().Context(), request.(CreateOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrg")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateOrgResponseObject); ok {
		return validResponse.VisitCreateOrgResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOrg operation middleware
func (sh *strictHandler) GetOrg(ctx echo.Context, orgId OrgId) error {
	var request GetOrgRequestObject

	request.OrgId = orgId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrg(ctx.Request().Context(), request.(GetOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrg")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOrgResponseObject); ok {
		return validResponse.VisitGetOrgResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdjustOrgCredits operation middleware
func (sh *strictHandler) AdjustOrgCredits(ctx echo.Context, orgId OrgId) error {
	var request AdjustOrgCreditsRequestObject

	request.OrgId = orgId

	var body AdjustOrgCreditsJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdjustOrgCredits(ctx.Request().Context(), request.(AdjustOrgCreditsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdjustOrgCredits")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdjustOrgCreditsResponseObject); ok {
		return validResponse.VisitAdjustOrgCreditsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DisableOrg operation middleware
func (sh *strictHandler) DisableOrg(ctx echo.Context, orgId OrgId) error {
	var request DisableOrgRequestObject

	request.OrgId = orgId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DisableOrg(ctx.Request().Context(), request.(DisableOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableOrg")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DisableOrgResponseObject); ok {
		return validResponse.VisitDisableOrgResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EnableOrg operation middleware
func (sh *strictHandler) EnableOrg(ctx echo.Context, orgId OrgId) error {
	var request EnableOrgRequestObject

	request.OrgId = orgId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnableOrg(ctx.Request().Context(), request.(EnableOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnableOrg")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EnableOrgResponseObject); ok {
		return validResponse.VisitEnableOrgResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SetOrgMaxAttendees operation middleware
func (sh *strictHandler) SetOrgMaxAttendees(ctx echo.Context, orgId OrgId) error {
	var request SetOrgMaxAttendeesRequestObject

	request.OrgId = orgId

	var body SetOrgMaxAttendeesJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetOrgMaxAttendees(ctx.Request().Context(), request.(SetOrgMaxAttendeesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetOrgMaxAttendees")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SetOrgMaxAttendeesResponseObject); ok {
		return validResponse.VisitSetOrgMaxAttendeesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListOrgUsers operation middleware
func (sh *strictHandler) ListOrgUsers(ctx echo.Context, orgId OrgId) error {
	var request ListOrgUsersRequestObject

	request.OrgId = orgId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrgUsers(ctx.Request().Context(), request.(ListOrgUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrgUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListOrgUsersResponseObject); ok {
		return validResponse.VisitListOrgUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateOrgUser operation middleware
func (sh *strictHandler) CreateOrgUser(ctx echo.Context, orgId OrgId) error {
	var request CreateOrgUserRequestObject

	request.OrgId = orgId

	var body CreateOrgUserJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrgUser(ctx.Request().Context(), request.(CreateOrgUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrgUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateOrgUserResponseObject); ok {
		return validResponse.VisitCreateOrgUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DisableOrgUser operation middleware
func (sh *strictHandler) DisableOrgUser(ctx echo.Context, orgId OrgId, userId UserId) error {
	var request DisableOrgUserRequestObject

	request.OrgId = orgId
	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DisableOrgUser(ctx.Request().Context(), request.(DisableOrgUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableOrgUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DisableOrgUserResponseObject); ok {
		return validResponse.VisitDisableOrgUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EnableOrgUser operation middleware
func (sh *strictHandler) EnableOrgUser(ctx echo.Context, orgId OrgId, userId UserId) error {
	var request EnableOrgUserRequestObject

	request.OrgId = orgId
	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnableOrgUser(ctx.Request().Context(), request.(EnableOrgUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnableOrgUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EnableOrgUserResponseObject); ok {
		return validResponse.VisitEnableOrgUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ResetOrgUserPassword operation middleware
func (sh *strictHandler) ResetOrgUserPassword(ctx echo.Context, orgId OrgId, userId UserId) error {
	var request ResetOrgUserPasswordRequestObject

	request.OrgId = orgId
	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResetOrgUserPassword(ctx.Request().Context(), request.(ResetOrgUserPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetOrgUserPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ResetOrgUserPasswordResponseObject); ok {
		return validResponse.VisitResetOrgUserPasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePlatformPassword operation middleware
func (sh *strictHandler) ChangePlatformPassword(ctx echo.Context) error {
	var request ChangePlatformPasswordRequestObject

	var body ChangePlatformPasswordJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePlatformPassword(ctx.Request().Context(), request.(ChangePlatformPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePlatformPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePlatformPasswordResponseObject); ok {
		return validResponse.VisitChangePlatformPasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx echo.Context) error {
	var request GetHealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx.Request().Context(), request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		return validResponse.VisitGetHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIJSON operation middleware
func (sh *strictHandler) GetOpenAPIJSON(ctx echo.Context) error {
	var request GetOpenAPIJSONRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIJSON(ctx.Request().Context(), request.(GetOpenAPIJSONRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIJSON")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIJSONResponseObject); ok {
		return validResponse.VisitGetOpenAPIJSONResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIYaml operation middleware
func (sh *strictHandler) GetOpenAPIYaml(ctx echo.Context) error {
	var request GetOpenAPIYamlRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIYaml(ctx.Request().Context(), request.(GetOpenAPIYamlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIYaml")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIYamlResponseObject); ok {
		return validResponse.VisitGetOpenAPIYamlResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzdb9y4Ef9XCLYPLU72rnPO9W7z5MsZbQonNuwExSEIDFoaaxlLpEJStjfG/u8Fv7T6oFZar9dxgT6d",
	"s6I4H7/hzHBmdA845nnBGTAl8ewBF0SQHBQI868TmlOl/6AMz/C3EsQCR5iRHPAMZ+ZhhGU8h5zoVQlc",
	"kzJTeHY4jXBO7mle5nh2MNX/osz9K8JqUej3KVOQgsDLZYRPr68l9FLi9mmQVH3vaXhvkb5Lqq0Loua1",
	"nc2zCAv4VlIBCZ4pUUKd0DUXOVF4hsuSJrgiIJWgLDX7f5IgegmU9uE2FJb6ZVlwJsGAciwEF/qPmDMF",
	"zGiNFEVGY6IoZ5OvkjP924rCXwVc4xn+y2SF9cQ+lRO7m6GSgIwFLfQmeIZ/LyVlICUCt8LzbJg4Sr6W",
	"Ur0VkFAlz+FbCdIwUghegFDUsppAphxc9a0/cLb3HQR/gxikRNFbQAJyfgsSxXZH3EVSa4E40XJyfwIs",
	"VXM8ezWdhkBZqfuz46J6/0u1nl99hVjprY8K+o5d84AEPDb/pQpy80eLVLUXEYIs8NID/4DhnuRFph+l",
	"PONKWYvuvF7MiWytfz8NLZSKxDfNhRDP+U8pF/lPBZcqFSC/ZXhIG4Y/T9dvG1lBQ6p5OycshTMi5R0X",
	"SS/UcSkEMHVZuIVBXTG4ayzIKfM4/jrEd4dAa7sg7wKIglOR9rPNmSKxahnVQcCoIgy3mr630NnDWsdj",
	"HOAlUQpYAtBcfhBa7u1mgI0wmk3W2rTXqka7r171QE5o1j5xrw8DytmOfUMmxGbl7NqwJa1D8+7Dx+Pz",
	"D0cnl8fn56fnoQOUg5QkhaBhCqsA68ZZmWXkKgPvqgfsUrOy2j0kxL+AZGr+PeBdrrrO8Q+iyBWRgKQi",
	"qtRgAtNG8xmXhTmndwxHWN7QooC61a+E4Tc1Ga84z4AwK2RCZZfguf7ZUXuDKLPxiHJGsghRhRIOEjGu",
	"UGw8AeI3j+BJgrilcZ9j3CMFDUFmj1kVIBOiYE/RHLprW6AYHj1Ns08IlxNIUhDHTIlFF5srkhEWwyW5",
	"ViBqCq0d2dicoeSSqLFsRquQ2N3OHmKahJKCAZuMcPi1zjItIVFcODL9z+2Ttq0UgrKYFiQzzxG/RmoO",
	"SPEbYEjNiUI5ScD8Zo0lxMIqjK/H0AjgY3cTjWqTNsNNARsIhQzglMFHmlfBrWsE9WDV1MRHyAsuiFgg",
	"v+YNEqBKwSBBnGULxFk8bKhrw9epSP8A5Txwk7HMmG6XrROiQCr0aoqAKUFBRojBnf7pmgqpcLTKZNZl",
	"hfWTEchxuEiHdjgV6UWZ50QsOjLrtyMvQY/cZ85TN6WueB8lRJ2FrgyKK5KFDmLbDA0pv76H3Qvrq2cP",
	"lWMksc5rtQVTqQ9u2C3WWFyXmnTee4zn6aQv7TCQE8ooS5FZuDYTH+lsOhlQK9LZOxzyS5C5UaKYFxQS",
	"RJni2nYtO2E+fNIRSpZVOcpA7MKg73HJiceh2nUo3Rp2OzbrCkD+GFh9ivbYkLC9ErUwIxRpOa2pcZya",
	"tjhb+vX/UDV/TgcfmTv/SK119GXejQbDAmH0u8nRTnhK2XD63r129l/TWhx51Eaz9B42YaTX+rhIL8cm",
	"NSK97Nln3X2jolHbYUi4C5CSchaQ8L6gAuRGR3cDEU2K1TXS34EIEC4BKzKifeO9elQmYilEdUEqDkNa",
	"OcuI0myvt8C15QBt7IF74y+HQ7xWLw6YpecxZJJ14iOphUg4g/jo8dneKn4I1GHR1Htyf+TjWi/GGxU6",
	"WqwMFSrM1TEuBVWLC+06q9RI8gysSrqqqh9YRJKcMqe2a8FzxNvu0xeWzXXZblnxMVeqMP7SWVIfSW9p",
	"yN8/6hSL+lEZpqaFpq4a2aLCJdV/6iwtnkN8s0cZIkxjvyepAuTu0+jo7N2+3paq5kVbP8ARvgVhvRie",
	"7h/sT93Fj+lb+Az/vD/d/9mcLDU32p6Y3x9waiv0VkLKma6W4H+C8sXTVp361XT6ZFVqTyJUpyaSxsjd",
	"9U35wlqNT6vxhXuUgyIJMbdJRVKprU8upIIcf9EvaCkndduYZAYube5cBiQ/DdiRqyP9zpPFk8neG+6X",
	"zcOkRAnLHWIQCoMBPAyLSJZxDJBA8qZWIdBlpjm/Y9ZLLSN8OD3oo1qJ4TsUET589dvo1Q0LCPiDzAHm",
	"LaEO/Bp74KUabRB6bQeOw0CiaXQj4JbfQLKpVmr+Ec8+dzzj5y/LL3VNnBsqtkBj6+nIvYF8UNhEIzms",
	"8wutpPCZTPM9hKzyrZPWoL9jJTdoGfdMlWyEnQ3VXE+ivOm1L+8aV6nvymLhTpsrzq24sJmCRMRcqzmD",
	"fRy1ULPNnro6z1btll04t3B36Zk9WyOHCxiPZ88VNZ1P00rs9WvTTfzaDk3RluxXdlDrng1YoE9ahsLg",
	"WSu52YWVBO8aL8xIXmDc6yal7bDnQe7BfW24q4HyQ0JdOyUfEev8K51gt04P64Nc7Yq5Q+OrUVkT3DzM",
	"u9bs27Y6K8LjNMpFKnt1ekKlzhwkjhrDSJ/DsqyWTNwM0TIaXGnHmrRMu8xITAsjgNYpA1SQ1HTP6r5X",
	"7ho2rdkmxU5zKIBe1HP8qwGCXWUG7dmNUf7+4CkRXDWwuiDWrxS8AOb92XMF/iGwTwvQWV8Db3RH1dwk",
	"o5RRRUmGvpW8cSEeOrWTBzMxtxxI+3ec67um6BAsiVu2cbydHo5evTEsNQYjq36Tm+solVW9W9sb9S3c",
	"3nO5mXvUwOHll7W4Tmrtwcdt3+cu7MDgqUjfVl2zXXiN4FziM2eKjeZ510Y/aqhXAC/QnaBKAdut/9jM",
	"rPXq33Z2CI6SBHHhZj6b7Wbrogiq5js29UwT1xN8egv+w24cdG+HA0VoKlHVq3xR/sgJ1Y4UbxBNIC+4",
	"OQyPAAHYbjA4ZttA4PrGLwqAY7YL/efkfq/RknlaGC5MlK83h3bkzntaUKMcesAgTOKPykL335KX5G83",
	"voGt6jpJeIrmmgs3OYPcmAUys3N3RCTyMSZVSvdRyLpb2yezaMvYOna4yw5QtCe7ugH3SFe+ZIR4lqzu",
	"Oi8KTsuhvhC2/MDTpn6DV7lP0g1X7vA6V583f/4rXWciqM9e/KmxdTxfNn3OUu9Lytgseto6bRnZZWmc",
	"2TGGUFl5M8cyebBfSm2fvw2Xf9wHW2MyvepADEUWazP/C2levR9kCqQ66zb1ULlt1tFCEtiPBrJKFzfH",
	"8WXniqtTyEv3YYaeCdFQrqYVnxRMARLUXqMT+YNAPdecOEwb3cldFZxaHwkEIsYHuAv4whdlO+dQZCSG",
	"ZjSreYG+zvFI09mqRV21pzbqUvueyP871C+6Q73BVabTTxqRV8xX39b1FaT953c7xMeTCEDjx8+oRJZX",
	"8/XJ6yck3vsJ9ycG9wXE+u6n5+NA+G+5Nf2fn1N4LlDiv2ssGbkl1H7N1uxXn9BbMJ+caz9QrS8oS/tm",
	"9tzU4r5nuLcnUQA7Onv374vTD9uaAUkSar+OPKtNwTa+yquGV7v9CcsHMoy0htTco4THZQ5Mob/pRX8f",
	"knxB8myE5H/qZRtJ7jdefa7pSM6QnxBdKSXw/ywIC/7n0fuTQcH1orDg7ktSn3O0JzBikqEEbiHjRW7T",
	"nlJkbq52NpkcvPrH/nR/un8we/36l191L+S/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
