// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx echo.Context) error
	// PlatformLogin Platform operator login
	// (POST /api/platform/login)
	PlatformLogin(ctx echo.Context) error
	// PlatformLogout Revoke the current platform token
	// (POST /api/platform/logout)
	PlatformLogout(ctx echo.Context) error
	// GetPlatformMe Current platform operator
	// (GET /api/platform/me)
	GetPlatformMe(ctx echo.Context) error
	// ChangePlatformPassword Change the platform operator password
	// (POST /api/platform/password)
	ChangePlatformPassword(ctx echo.Context) error
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx echo.Context) error
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx echo.Context) error
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiInfo(ctx)
	return err
}

// PlatformLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PlatformLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlatformLogin(ctx)
	return err
}

// PlatformLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PlatformLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PlatformLogout(ctx)
	return err
}

// GetPlatformMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlatformMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlatformMe(ctx)
	return err
}

// ChangePlatformPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePlatformPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePlatformPassword(ctx)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// GetOpenAPIJSON converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIJSON(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIJSON(ctx)
	return err
}

// GetOpenAPIYaml converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPIYaml(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPIYaml(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz, options.OperationMiddlewares["getHealthz"]...)
	router.GET(options.BaseURL+"/api", wrapper.GetApiInfo, options.OperationMiddlewares["getApiInfo"]...)
	router.GET(options.BaseURL+"/openapi.yaml", wrapper.GetOpenAPIYaml, options.OperationMiddlewares["getOpenAPIYaml"]...)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPIJSON, options.OperationMiddlewares["getOpenAPIJSON"]...)
	router.POST(options.BaseURL+"/api/platform/login", wrapper.PlatformLogin, options.OperationMiddlewares["platformLogin"]...)
	router.POST(options.BaseURL+"/api/platform/logout", wrapper.PlatformLogout, options.OperationMiddlewares["platformLogout"]...)
	router.GET(options.BaseURL+"/api/platform/me", wrapper.GetPlatformMe, options.OperationMiddlewares["getPlatformMe"]...)
	router.POST(options.BaseURL+"/api/platform/password", wrapper.ChangePlatformPassword, options.OperationMiddlewares["changePlatformPassword"]...)

}

type ErrorJSONResponse Error

type GetApiInfoRequestObject struct {
}

type GetApiInfoResponseObject interface {
	VisitGetApiInfoResponse(w http.ResponseWriter) error
}

type GetApiInfo200JSONResponse ApiInfo

func (response GetApiInfo200JSONResponse) VisitGetApiInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLoginRequestObject struct {
	Body *PlatformLoginJSONRequestBody
}

type PlatformLoginResponseObject interface {
	VisitPlatformLoginResponse(w http.ResponseWriter) error
}

type PlatformLogin200JSONResponse SessionToken

func (response PlatformLogin200JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogin401JSONResponse struct{ ErrorJSONResponse }

func (response PlatformLogin401JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogin429JSONResponse Error

func (response PlatformLogin429JSONResponse) VisitPlatformLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type PlatformLogoutRequestObject struct {
}

type PlatformLogoutResponseObject interface {
	VisitPlatformLogoutResponse(w http.ResponseWriter) error
}

type PlatformLogout204Response struct {
}

func (response PlatformLogout204Response) VisitPlatformLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PlatformLogout401JSONResponse struct{ ErrorJSONResponse }

func (response PlatformLogout401JSONResponse) VisitPlatformLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlatformMeRequestObject struct {
}

type GetPlatformMeResponseObject interface {
	VisitGetPlatformMeResponse(w http.ResponseWriter) error
}

type GetPlatformMe200JSONResponse PlatformMe

func (response GetPlatformMe200JSONResponse) VisitGetPlatformMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlatformMe401JSONResponse struct{ ErrorJSONResponse }

func (response GetPlatformMe401JSONResponse) VisitGetPlatformMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPasswordRequestObject struct {
	Body *ChangePlatformPasswordJSONRequestBody
}

type ChangePlatformPasswordResponseObject interface {
	VisitChangePlatformPasswordResponse(w http.ResponseWriter) error
}

type ChangePlatformPassword200JSONResponse SessionToken

func (response ChangePlatformPassword200JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPassword400JSONResponse struct{ ErrorJSONResponse }

func (response ChangePlatformPassword400JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePlatformPassword401JSONResponse Error

func (response ChangePlatformPassword401JSONResponse) VisitChangePlatformPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Healthz

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz500JSONResponse Error

func (response GetHealthz500JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse Healthz

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIJSONRequestObject struct {
}

type GetOpenAPIJSONResponseObject interface {
	VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error
}

type GetOpenAPIJSON200JSONResponse map[string]interface{}

func (response GetOpenAPIJSON200JSONResponse) VisitGetOpenAPIJSONResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPIYamlRequestObject struct {
}

type GetOpenAPIYamlResponseObject interface {
	VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error
}

type GetOpenAPIYaml200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenAPIYaml200ApplicationyamlResponse) VisitGetOpenAPIYamlResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetApiInfo Service metadata
	// (GET /api)
	GetApiInfo(ctx context.Context, request GetApiInfoRequestObject) (GetApiInfoResponseObject, error)
	// PlatformLogin Platform operator login
	// (POST /api/platform/login)
	PlatformLogin(ctx context.Context, request PlatformLoginRequestObject) (PlatformLoginResponseObject, error)
	// PlatformLogout Revoke the current platform token
	// (POST /api/platform/logout)
	PlatformLogout(ctx context.Context, request PlatformLogoutRequestObject) (PlatformLogoutResponseObject, error)
	// GetPlatformMe Current platform operator
	// (GET /api/platform/me)
	GetPlatformMe(ctx context.Context, request GetPlatformMeRequestObject) (GetPlatformMeResponseObject, error)
	// ChangePlatformPassword Change the platform operator password
	// (POST /api/platform/password)
	ChangePlatformPassword(ctx context.Context, request ChangePlatformPasswordRequestObject) (ChangePlatformPasswordResponseObject, error)
	// GetHealthz Liveness and database ping
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetOpenAPIJSON OpenAPI document (JSON)
	// (GET /openapi.json)
	GetOpenAPIJSON(ctx context.Context, request GetOpenAPIJSONRequestObject) (GetOpenAPIJSONResponseObject, error)
	// GetOpenAPIYaml OpenAPI document (YAML)
	// (GET /openapi.yaml)
	GetOpenAPIYaml(ctx context.Context, request GetOpenAPIYamlRequestObject) (GetOpenAPIYamlResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiInfo operation middleware
func (sh *strictHandler) GetApiInfo(ctx echo.Context) error {
	var request GetApiInfoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiInfo(ctx.Request().Context(), request.(GetApiInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiInfoResponseObject); ok {
		return validResponse.VisitGetApiInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PlatformLogin operation middleware
func (sh *strictHandler) PlatformLogin(ctx echo.Context) error {
	var request PlatformLoginRequestObject

	var body PlatformLoginJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformLogin(ctx.Request().Context(), request.(PlatformLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PlatformLoginResponseObject); ok {
		return validResponse.VisitPlatformLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PlatformLogout operation middleware
func (sh *strictHandler) PlatformLogout(ctx echo.Context) error {
	var request PlatformLogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PlatformLogout(ctx.Request().Context(), request.(PlatformLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlatformLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PlatformLogoutResponseObject); ok {
		return validResponse.VisitPlatformLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPlatformMe operation middleware
func (sh *strictHandler) GetPlatformMe(ctx echo.Context) error {
	var request GetPlatformMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlatformMe(ctx.Request().Context(), request.(GetPlatformMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlatformMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPlatformMeResponseObject); ok {
		return validResponse.VisitGetPlatformMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePlatformPassword operation middleware
func (sh *strictHandler) ChangePlatformPassword(ctx echo.Context) error {
	var request ChangePlatformPasswordRequestObject

	var body ChangePlatformPasswordJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePlatformPassword(ctx.Request().Context(), request.(ChangePlatformPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePlatformPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePlatformPasswordResponseObject); ok {
		return validResponse.VisitChangePlatformPasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx echo.Context) error {
	var request GetHealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx.Request().Context(), request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		return validResponse.VisitGetHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIJSON operation middleware
func (sh *strictHandler) GetOpenAPIJSON(ctx echo.Context) error {
	var request GetOpenAPIJSONRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIJSON(ctx.Request().Context(), request.(GetOpenAPIJSONRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIJSON")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIJSONResponseObject); ok {
		return validResponse.VisitGetOpenAPIJSONResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPIYaml operation middleware
func (sh *strictHandler) GetOpenAPIYaml(ctx echo.Context) error {
	var request GetOpenAPIYamlRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPIYaml(ctx.Request().Context(), request.(GetOpenAPIYamlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPIYaml")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPIYamlResponseObject); ok {
		return validResponse.VisitGetOpenAPIYamlResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhfb9s2EP8qBLeHDVVsp026Tn1Ks2DLkD+G0z0UQRAw0sViLZEMeXLiBf7uAynSliw5drB42Esri6e7",
	"3/3uD+/yTBNZKClAoKHxM9VglBQG3I8TraW2D4kUCALtI1Mq5wlDLkX/u5HCvjNJBgWzTz9quKcx/aG/",
	"1NqvTk2/0jafzyOagkk0V1YJjemX0nABxhDwEpHX6EAcKX4q7qV9VFoq0MgrdKlM3P8coXAPOFNAY2pQ",
	"czGm8yi8YFqzmf0tWAFWEJ5YoXJ7NJa5RAQ9o1H7c5UxsyJ/PugSNMiSSVMQkky+G0tdvFPS4FiDecjb",
	"n84jquGh5BpSGl9X+ILdoDaqHL1ZfCzvvkOC1u5xxsQYhsyYR6nTETyUYLBNVFJqDQJvlRfs5ErAY0Og",
	"4OIMxBgzGn/ahLtlYEVdF/ZFbq1glekK5acXX09GF0dntyej0eWoi/4CjGFj6HRLV6ScOp9EmefszmpF",
	"XcJGryyUpfYuJ/4AlmP2d0du3rl/G2n+G0N2xwwQgwxLQyMKoiyspVK5KD8KG/QJVwrqnC2dkZOaj3dS",
	"5sCEfW9AT3myLrX3mOJdtFUFfy91wZDGNGUIe8gLaMuuECMndGnT6eniZpgztMrP5JiLtbn5Yk6WBnSo",
	"2YI9hXz8eLAJ4eLDiL6YhAHjObSR1Y1vaa3LxBUYw6X4Kicg2kbgSXEN5pbhtrGIKAZVK10UmAZN3ClR",
	"OeMC4Qk/Ew1YagEpkSKfESmSzQGuLER1dG3XXN4lpeY4u7Ld2sfTM1qhaaMMjBPLAkMZAN9rWRBVTxnq",
	"bwGX65W2BYYMUVU3CfdXw4oVabh95GJMkgySyR4XhAnLwZ7hCMSXBjkanvasWo7NmrEHNKJT0KbSOOjt",
	"9wauBhUIW1Ax/dAb9D64DMPM+d5375/pGFw0Kw+5FLb50N8Bw00WNW/Z94PBm92xwUTXLcsMT4gvW8Ir",
	"qYiasiiYntGYXvmjApClDJnlhY2NTQgzMwgFvbEfWC/7IVL93IXKBl6aDq+HKxH17fiLTGdv5nNno5k3",
	"c9r2+/kOeW9UeQf5DhsxZZIApJB+JpiBz3xuiMnko6hKcx7Rg8H+OnML/GGYiujB+1+3lm6Eu12JuQ9S",
	"iHoI8pq4yxK3CryVa1F/0C5aRx7RMJUTSF9LRK0b0fi63Yeub+Y3de9HzowLg59eFt2HhPa3DQ8FvFTx",
	"tftlh8lXs9KResfevRDmXTN7vErnwvB2jNYngpBbTY+q2BkCU9upqyqS9y6Wi1y2zb66+QxhRMAjkQJs",
	"q2/GyE/Q3vZwOb/uolF1j+v/s04V4JHEofWtyhK4tl0NXtOudpl5DrHD20o+UttN1mRhthzm19VzmPd3",
	"GJ9goiM04YLmhlRY3VJ7+IbG167ofwl4UpAgpG6CAB12dWv/w3/pvNQkDYtUKdiU8Wqla15uZ3wK7k8K",
	"tg8s5JUddtdMNX6u6wXA61LgUoE4Gp7+eXV58W/TgKWpm1JZPqwtBY3VdDFst/jwOIgD0nQ+HKUyKQvb",
	"in+yQj9v8nzGinwLz79ZsVd5HhQvd1NvMiZhhl6SsrqZrHX829H52UbHrVC3435tBm1cb1kd1xKWkxSm",
	"kEtlNdGIljr3m0fc7++//6U36A16+/Hh4cdPdH4z/2cA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
