// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5568' | (string & {});
};

export type Error = {
    code: string;
    message: string;
    requestId?: string | null;
};

export type Healthz = {
    ok: boolean;
    service: string;
    ts: string;
    /**
     * Database status
     */
    db?: 'up' | 'down' | 'skipped';
};

export type ApiInfo = {
    name: string;
    phase: string;
    stack: string;
    docs: Array<string>;
};

export type PlatformLoginRequest = {
    username: string;
    password: string;
};

export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
};

export type SessionToken = {
    /**
     * Bearer token plaintext; returned only once
     */
    token: string;
    expires_at: string;
};

export type PlatformMe = {
    username: string;
};

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzErrors = {
    /**
     * Unexpected server error
     */
    500: Error;
    /**
     * Service or database unavailable
     */
    503: Healthz;
};

export type GetHealthzError = GetHealthzErrors[keyof GetHealthzErrors];

export type GetHealthzResponses = {
    /**
     * Service is healthy
     */
    200: Healthz;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiInfoResponses = {
    /**
     * Basic service info
     */
    200: ApiInfo;
};

export type GetApiInfoResponse = GetApiInfoResponses[keyof GetApiInfoResponses];

export type GetOpenApiYamlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.yaml';
};

export type GetOpenApiYamlResponses = {
    /**
     * OpenAPI YAML
     */
    200: string;
};

export type GetOpenApiYamlResponse = GetOpenApiYamlResponses[keyof GetOpenApiYamlResponses];

export type GetOpenApijsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenApijsonResponses = {
    /**
     * OpenAPI JSON
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenApijsonResponse = GetOpenApijsonResponses[keyof GetOpenApijsonResponses];

export type PlatformLoginData = {
    body: PlatformLoginRequest;
    path?: never;
    query?: never;
    url: '/api/platform/login';
};

export type PlatformLoginErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    429: Error;
};

export type PlatformLoginError = PlatformLoginErrors[keyof PlatformLoginErrors];

export type PlatformLoginResponses = {
    /**
     * Login succeeded; the token is shown once
     */
    200: SessionToken;
};

export type PlatformLoginResponse = PlatformLoginResponses[keyof PlatformLoginResponses];

export type PlatformLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/logout';
};

export type PlatformLogoutErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type PlatformLogoutError = PlatformLogoutErrors[keyof PlatformLogoutErrors];

export type PlatformLogoutResponses = {
    /**
     * Token revoked
     */
    204: void;
};

export type PlatformLogoutResponse = PlatformLogoutResponses[keyof PlatformLogoutResponses];

export type GetPlatformMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/me';
};

export type GetPlatformMeErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type GetPlatformMeError = GetPlatformMeErrors[keyof GetPlatformMeErrors];

export type GetPlatformMeResponses = {
    /**
     * Current operator
     */
    200: PlatformMe;
};

export type GetPlatformMeResponse = GetPlatformMeResponses[keyof GetPlatformMeResponses];

export type ChangePlatformPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/platform/password';
};

export type ChangePlatformPasswordErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type ChangePlatformPasswordError = ChangePlatformPasswordErrors[keyof ChangePlatformPasswordErrors];

export type ChangePlatformPasswordResponses = {
    /**
     * Password changed; the new token is shown once
     */
    200: SessionToken;
};

export type ChangePlatformPasswordResponse = ChangePlatformPasswordResponses[keyof ChangePlatformPasswordResponses];
