// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5568' | (string & {});
};

export type Error = {
    code: string;
    message: string;
    requestId?: string | null;
};

export type Healthz = {
    ok: boolean;
    service: string;
    ts: string;
    /**
     * Database status
     */
    db?: 'up' | 'down' | 'skipped';
    /**
     * Redis status; informational, it does not change ok
     */
    redis?: 'up' | 'down' | 'skipped';
};

export type ApiInfo = {
    name: string;
    phase: string;
    stack: string;
    docs: Array<string>;
};

export type PlatformLoginRequest = {
    username: string;
    password: string;
};

export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
};

export type SessionToken = {
    /**
     * Bearer token plaintext; returned only once
     */
    token: string;
    expires_at: string;
};

export type PlatformMe = {
    username: string;
};

export type OrgStatus = 'active' | 'disabled';

export type OrgSummary = {
    id: string;
    name: string;
    contact: string;
    status: OrgStatus;
    /**
     * Remaining event credits
     */
    event_credits: number;
    /**
     * Default attendee limit copied into new events
     */
    max_attendees: number;
    created_at: string;
};

export type OrgPage = {
    items: Array<OrgSummary>;
    total: number;
};

export type OrgDetail = {
    org: OrgSummary;
    /**
     * Latest 20 entries, newest first
     */
    ledger: Array<LedgerEntry>;
};

export type LedgerEntry = {
    id: string;
    delta: number;
    balance_after: number;
    reason: string;
    event_id?: string | null;
    /**
     * principal_type of the token that made the change
     */
    operator_type: string;
    operator_id: string;
    created_at: string;
};

export type CreateOrgRequest = {
    name: string;
    contact?: string;
    event_credits: number;
    max_attendees: number;
};

export type AdjustCreditsRequest = {
    /**
     * Non-zero; negative removes credits
     */
    delta: number;
    reason: string;
};

export type SetMaxAttendeesRequest = {
    max_attendees: number;
};

export type OrgUserStatus = 'active' | 'disabled';

export type OrgUser = {
    id: string;
    name: string;
    email: string;
    status: OrgUserStatus;
    created_at: string;
};

export type OrgUserWithPassword = {
    user: OrgUser;
    /**
     * Temporary password; returned only once
     */
    password: string;
};

export type OneTimePassword = {
    /**
     * Temporary password; returned only once
     */
    password: string;
};

export type CreateOrgUserRequest = {
    name: string;
    email: string;
};

export type OrganizationLoginRequest = {
    email: string;
    password: string;
};

export type OrganizationSession = {
    /**
     * Bearer token plaintext; returned only once
     */
    token: string;
    expires_at: string;
    org_id: string;
};

export type OrganizationMe = {
    name: string;
    email: string;
    org_id: string;
    org_name: string;
    /**
     * Remaining event credits of the organization
     */
    event_credits: number;
};

export type EventStatus = 'draft' | 'ready' | 'closed';

export type CheckinMode = 'geo' | 'direct';

export type Event = {
    id: string;
    public_id: string;
    name: string;
    status: EventStatus;
    checkin_mode: CheckinMode;
    /**
     * GCJ-02 latitude
     */
    center_lat?: number | null;
    /**
     * GCJ-02 longitude
     */
    center_lng?: number | null;
    radius_m: number;
    checkin_start?: string | null;
    checkin_end?: string | null;
    allow_multi_win: boolean;
    max_attendees: number;
    attendee_count: number;
    prize_count: number;
    /**
     * Whether this event has already used its credit
     */
    credit_consumed: boolean;
    created_at: string;
};

export type EventPage = {
    items: Array<Event>;
    total: number;
};

export type CreateEventRequest = {
    name: string;
};

/**
 * Only the fields present change.
 */
export type UpdateEventRequest = {
    name?: string;
    checkin_mode?: CheckinMode;
    center_lat?: number;
    center_lng?: number;
    radius_m?: number;
    checkin_start?: string;
    checkin_end?: string;
    allow_multi_win?: boolean;
    status?: EventStatus;
};

export type EventEntry = {
    public_id: string;
    path: string;
};

export type Prize = {
    id: string;
    name: string;
    gift: string;
    quota: number;
    sort_no: number;
};

export type PrizeInput = {
    name: string;
    gift?: string;
    quota: number;
    sort_no: number;
};

export type PrizeUpdate = {
    name?: string;
    gift?: string;
    quota?: number;
    sort_no?: number;
};

export type Attendee = {
    id: string;
    name: string;
    dept: string;
    phone_last4: string;
    status: string;
    created_at: string;
};

export type AttendeePage = {
    items: Array<Attendee>;
    total: number;
};

export type AttendeeInput = {
    name: string;
    dept?: string;
    /**
     * Full phone or its last four digits; only the last four are stored
     */
    phone: string;
};

export type AttendeeUpdate = {
    name?: string;
    dept?: string;
    phone?: string;
};

export type ImportResult = {
    imported: number;
};

export type ImportRowError = {
    /**
     * Spreadsheet row number; the header is row 1
     */
    row: number;
    reason: string;
};

export type ImportError = {
    code: string;
    message: string;
    rows: Array<ImportRowError>;
};

export type EventId = string;

export type PrizeId = string;

export type AttendeeId = string;

export type UserId = string;

export type OrgId = string;

export type Offset = number;

export type Limit = number;

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzErrors = {
    /**
     * Unexpected server error
     */
    500: Error;
    /**
     * Service or database unavailable
     */
    503: Healthz;
};

export type GetHealthzError = GetHealthzErrors[keyof GetHealthzErrors];

export type GetHealthzResponses = {
    /**
     * Service is healthy
     */
    200: Healthz;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiInfoResponses = {
    /**
     * Basic service info
     */
    200: ApiInfo;
};

export type GetApiInfoResponse = GetApiInfoResponses[keyof GetApiInfoResponses];

export type GetOpenApiYamlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.yaml';
};

export type GetOpenApiYamlResponses = {
    /**
     * OpenAPI YAML
     */
    200: string;
};

export type GetOpenApiYamlResponse = GetOpenApiYamlResponses[keyof GetOpenApiYamlResponses];

export type GetOpenApijsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenApijsonResponses = {
    /**
     * OpenAPI JSON
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenApijsonResponse = GetOpenApijsonResponses[keyof GetOpenApijsonResponses];

export type PlatformLoginData = {
    body: PlatformLoginRequest;
    path?: never;
    query?: never;
    url: '/api/platform/login';
};

export type PlatformLoginErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    429: Error;
};

export type PlatformLoginError = PlatformLoginErrors[keyof PlatformLoginErrors];

export type PlatformLoginResponses = {
    /**
     * Login succeeded; the token is shown once
     */
    200: SessionToken;
};

export type PlatformLoginResponse = PlatformLoginResponses[keyof PlatformLoginResponses];

export type PlatformLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/logout';
};

export type PlatformLogoutErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type PlatformLogoutError = PlatformLogoutErrors[keyof PlatformLogoutErrors];

export type PlatformLogoutResponses = {
    /**
     * Token revoked
     */
    204: void;
};

export type PlatformLogoutResponse = PlatformLogoutResponses[keyof PlatformLogoutResponses];

export type GetPlatformMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/me';
};

export type GetPlatformMeErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type GetPlatformMeError = GetPlatformMeErrors[keyof GetPlatformMeErrors];

export type GetPlatformMeResponses = {
    /**
     * Current operator
     */
    200: PlatformMe;
};

export type GetPlatformMeResponse = GetPlatformMeResponses[keyof GetPlatformMeResponses];

export type ChangePlatformPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/platform/password';
};

export type ChangePlatformPasswordErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type ChangePlatformPasswordError = ChangePlatformPasswordErrors[keyof ChangePlatformPasswordErrors];

export type ChangePlatformPasswordResponses = {
    /**
     * Password changed; the new token is shown once
     */
    200: SessionToken;
};

export type ChangePlatformPasswordResponse = ChangePlatformPasswordResponses[keyof ChangePlatformPasswordResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/platform/orgs';
};

export type ListOrgsErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * One page of organizations
     */
    200: OrgPage;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type CreateOrgData = {
    body: CreateOrgRequest;
    path?: never;
    query?: never;
    url: '/api/platform/orgs';
};

export type CreateOrgErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type CreateOrgError = CreateOrgErrors[keyof CreateOrgErrors];

export type CreateOrgResponses = {
    /**
     * Organization opened
     */
    201: OrgSummary;
};

export type CreateOrgResponse = CreateOrgResponses[keyof CreateOrgResponses];

export type GetOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}';
};

export type GetOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * Organization detail
     */
    200: OrgDetail;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type DisableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/disable';
};

export type DisableOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type DisableOrgError = DisableOrgErrors[keyof DisableOrgErrors];

export type DisableOrgResponses = {
    /**
     * Organization is disabled
     */
    204: void;
};

export type DisableOrgResponse = DisableOrgResponses[keyof DisableOrgResponses];

export type EnableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/enable';
};

export type EnableOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type EnableOrgError = EnableOrgErrors[keyof EnableOrgErrors];

export type EnableOrgResponses = {
    /**
     * Organization is active
     */
    204: void;
};

export type EnableOrgResponse = EnableOrgResponses[keyof EnableOrgResponses];

export type AdjustOrgCreditsData = {
    body: AdjustCreditsRequest;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/credits';
};

export type AdjustOrgCreditsErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type AdjustOrgCreditsError = AdjustOrgCreditsErrors[keyof AdjustOrgCreditsErrors];

export type AdjustOrgCreditsResponses = {
    /**
     * The ledger entry written
     */
    200: LedgerEntry;
};

export type AdjustOrgCreditsResponse = AdjustOrgCreditsResponses[keyof AdjustOrgCreditsResponses];

export type SetOrgMaxAttendeesData = {
    body: SetMaxAttendeesRequest;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/max-attendees';
};

export type SetOrgMaxAttendeesErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type SetOrgMaxAttendeesError = SetOrgMaxAttendeesErrors[keyof SetOrgMaxAttendeesErrors];

export type SetOrgMaxAttendeesResponses = {
    /**
     * Limit updated
     */
    204: void;
};

export type SetOrgMaxAttendeesResponse = SetOrgMaxAttendeesResponses[keyof SetOrgMaxAttendeesResponses];

export type ListOrgUsersData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/users';
};

export type ListOrgUsersErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type ListOrgUsersError = ListOrgUsersErrors[keyof ListOrgUsersErrors];

export type ListOrgUsersResponses = {
    /**
     * Admins, oldest first
     */
    200: Array<OrgUser>;
};

export type ListOrgUsersResponse = ListOrgUsersResponses[keyof ListOrgUsersResponses];

export type CreateOrgUserData = {
    body: CreateOrgUserRequest;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/users';
};

export type CreateOrgUserErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type CreateOrgUserError = CreateOrgUserErrors[keyof CreateOrgUserErrors];

export type CreateOrgUserResponses = {
    /**
     * Admin created; the password is shown once
     */
    201: OrgUserWithPassword;
};

export type CreateOrgUserResponse = CreateOrgUserResponses[keyof CreateOrgUserResponses];

export type ResetOrgUserPasswordData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/users/{userId}/reset-password';
};

export type ResetOrgUserPasswordErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type ResetOrgUserPasswordError = ResetOrgUserPasswordErrors[keyof ResetOrgUserPasswordErrors];

export type ResetOrgUserPasswordResponses = {
    /**
     * New one-time password
     */
    200: OneTimePassword;
};

export type ResetOrgUserPasswordResponse = ResetOrgUserPasswordResponses[keyof ResetOrgUserPasswordResponses];

export type DisableOrgUserData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/users/{userId}/disable';
};

export type DisableOrgUserErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type DisableOrgUserError = DisableOrgUserErrors[keyof DisableOrgUserErrors];

export type DisableOrgUserResponses = {
    /**
     * Admin is disabled
     */
    204: void;
};

export type DisableOrgUserResponse = DisableOrgUserResponses[keyof DisableOrgUserResponses];

export type EnableOrgUserData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/users/{userId}/enable';
};

export type EnableOrgUserErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type EnableOrgUserError = EnableOrgUserErrors[keyof EnableOrgUserErrors];

export type EnableOrgUserResponses = {
    /**
     * Admin is active
     */
    204: void;
};

export type EnableOrgUserResponse = EnableOrgUserResponses[keyof EnableOrgUserResponses];

export type OrganizationLoginData = {
    body: OrganizationLoginRequest;
    path?: never;
    query?: never;
    url: '/api/organization/login';
};

export type OrganizationLoginErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    429: Error;
};

export type OrganizationLoginError = OrganizationLoginErrors[keyof OrganizationLoginErrors];

export type OrganizationLoginResponses = {
    /**
     * Login succeeded; the token is shown once
     */
    200: OrganizationSession;
};

export type OrganizationLoginResponse = OrganizationLoginResponses[keyof OrganizationLoginResponses];

export type OrganizationLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organization/logout';
};

export type OrganizationLogoutErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type OrganizationLogoutError = OrganizationLogoutErrors[keyof OrganizationLogoutErrors];

export type OrganizationLogoutResponses = {
    /**
     * Token revoked
     */
    204: void;
};

export type OrganizationLogoutResponse = OrganizationLogoutResponses[keyof OrganizationLogoutResponses];

export type GetOrganizationMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organization/me';
};

export type GetOrganizationMeErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type GetOrganizationMeError = GetOrganizationMeErrors[keyof GetOrganizationMeErrors];

export type GetOrganizationMeResponses = {
    /**
     * Current admin
     */
    200: OrganizationMe;
};

export type GetOrganizationMeResponse = GetOrganizationMeResponses[keyof GetOrganizationMeResponses];

export type ChangeOrganizationPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/organization/password';
};

export type ChangeOrganizationPasswordErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type ChangeOrganizationPasswordError = ChangeOrganizationPasswordErrors[keyof ChangeOrganizationPasswordErrors];

export type ChangeOrganizationPasswordResponses = {
    /**
     * Password changed; the new token is shown once
     */
    200: SessionToken;
};

export type ChangeOrganizationPasswordResponse = ChangeOrganizationPasswordResponses[keyof ChangeOrganizationPasswordResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/organization/events';
};

export type ListEventsErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    /**
     * OK
     */
    200: EventPage;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: CreateEventRequest;
    path?: never;
    query?: never;
    url: '/api/organization/events';
};

export type CreateEventErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * OK
     */
    201: Event;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetEventData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}';
};

export type GetEventErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type UpdateEventData = {
    body: UpdateEventRequest;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}';
};

export type UpdateEventErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetEventEntryData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/entry';
};

export type GetEventEntryErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type GetEventEntryError = GetEventEntryErrors[keyof GetEventEntryErrors];

export type GetEventEntryResponses = {
    /**
     * OK
     */
    200: EventEntry;
};

export type GetEventEntryResponse = GetEventEntryResponses[keyof GetEventEntryResponses];

export type ListPrizesData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/prizes';
};

export type ListPrizesErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type ListPrizesError = ListPrizesErrors[keyof ListPrizesErrors];

export type ListPrizesResponses = {
    /**
     * OK
     */
    200: Array<Prize>;
};

export type ListPrizesResponse = ListPrizesResponses[keyof ListPrizesResponses];

export type CreatePrizeData = {
    body: PrizeInput;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/prizes';
};

export type CreatePrizeErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type CreatePrizeError = CreatePrizeErrors[keyof CreatePrizeErrors];

export type CreatePrizeResponses = {
    /**
     * OK
     */
    201: Prize;
};

export type CreatePrizeResponse = CreatePrizeResponses[keyof CreatePrizeResponses];

export type DeletePrizeData = {
    body?: never;
    path: {
        eventId: string;
        prizeId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/prizes/{prizeId}';
};

export type DeletePrizeErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type DeletePrizeError = DeletePrizeErrors[keyof DeletePrizeErrors];

export type DeletePrizeResponses = {
    /**
     * Done
     */
    204: void;
};

export type DeletePrizeResponse = DeletePrizeResponses[keyof DeletePrizeResponses];

export type UpdatePrizeData = {
    body: PrizeUpdate;
    path: {
        eventId: string;
        prizeId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/prizes/{prizeId}';
};

export type UpdatePrizeErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type UpdatePrizeError = UpdatePrizeErrors[keyof UpdatePrizeErrors];

export type UpdatePrizeResponses = {
    /**
     * OK
     */
    200: Prize;
};

export type UpdatePrizeResponse = UpdatePrizeResponses[keyof UpdatePrizeResponses];

export type ListAttendeesData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/organization/events/{eventId}/attendees';
};

export type ListAttendeesErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type ListAttendeesError = ListAttendeesErrors[keyof ListAttendeesErrors];

export type ListAttendeesResponses = {
    /**
     * OK
     */
    200: AttendeePage;
};

export type ListAttendeesResponse = ListAttendeesResponses[keyof ListAttendeesResponses];

export type CreateAttendeeData = {
    body: AttendeeInput;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/attendees';
};

export type CreateAttendeeErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type CreateAttendeeError = CreateAttendeeErrors[keyof CreateAttendeeErrors];

export type CreateAttendeeResponses = {
    /**
     * OK
     */
    201: Attendee;
};

export type CreateAttendeeResponse = CreateAttendeeResponses[keyof CreateAttendeeResponses];

export type DeleteAttendeeData = {
    body?: never;
    path: {
        eventId: string;
        attendeeId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/attendees/{attendeeId}';
};

export type DeleteAttendeeErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type DeleteAttendeeError = DeleteAttendeeErrors[keyof DeleteAttendeeErrors];

export type DeleteAttendeeResponses = {
    /**
     * Done
     */
    204: void;
};

export type DeleteAttendeeResponse = DeleteAttendeeResponses[keyof DeleteAttendeeResponses];

export type UpdateAttendeeData = {
    body: AttendeeUpdate;
    path: {
        eventId: string;
        attendeeId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/attendees/{attendeeId}';
};

export type UpdateAttendeeErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type UpdateAttendeeError = UpdateAttendeeErrors[keyof UpdateAttendeeErrors];

export type UpdateAttendeeResponses = {
    /**
     * OK
     */
    200: Attendee;
};

export type UpdateAttendeeResponse = UpdateAttendeeResponses[keyof UpdateAttendeeResponses];

export type ImportAttendeesData = {
    body: {
        file: Blob | File;
    };
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/attendees/import';
};

export type ImportAttendeesErrors = {
    /**
     * The file or some rows are invalid; nothing was written
     */
    400: ImportError;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type ImportAttendeesError = ImportAttendeesErrors[keyof ImportAttendeesErrors];

export type ImportAttendeesResponses = {
    /**
     * Rows appended
     */
    200: ImportResult;
};

export type ImportAttendeesResponse = ImportAttendeesResponses[keyof ImportAttendeesResponses];

export type ExportAttendeesData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/exports/attendees';
};

export type ExportAttendeesErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type ExportAttendeesError = ExportAttendeesErrors[keyof ExportAttendeesErrors];

export type ExportAttendeesResponses = {
    /**
     * xlsx workbook
     */
    200: Blob | File;
};

export type ExportAttendeesResponse = ExportAttendeesResponses[keyof ExportAttendeesResponses];

export type GetEventQrCodeData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/organization/events/{eventId}/entry/qrcode';
};

export type GetEventQrCodeErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    500: Error;
    /**
     * Business error
     */
    503: Error;
};

export type GetEventQrCodeError = GetEventQrCodeErrors[keyof GetEventQrCodeErrors];

export type GetEventQrCodeResponses = {
    /**
     * PNG image
     */
    200: Blob | File;
};

export type GetEventQrCodeResponse = GetEventQrCodeResponses[keyof GetEventQrCodeResponses];
