// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5568' | (string & {});
};

export type Error = {
    code: string;
    message: string;
    requestId?: string | null;
};

export type Healthz = {
    ok: boolean;
    service: string;
    ts: string;
    /**
     * Database status
     */
    db?: 'up' | 'down' | 'skipped';
};

export type ApiInfo = {
    name: string;
    phase: string;
    stack: string;
    docs: Array<string>;
};

export type PlatformLoginRequest = {
    username: string;
    password: string;
};

export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
};

export type SessionToken = {
    /**
     * Bearer token plaintext; returned only once
     */
    token: string;
    expires_at: string;
};

export type PlatformMe = {
    username: string;
};

export type OrgStatus = 'active' | 'disabled';

export type OrgSummary = {
    id: string;
    name: string;
    contact: string;
    status: OrgStatus;
    /**
     * Remaining event credits
     */
    event_credits: number;
    /**
     * Default attendee limit copied into new events
     */
    max_attendees: number;
    created_at: string;
};

export type OrgPage = {
    items: Array<OrgSummary>;
    total: number;
};

export type OrgDetail = {
    org: OrgSummary;
    /**
     * Latest 20 entries, newest first
     */
    ledger: Array<LedgerEntry>;
};

export type LedgerEntry = {
    id: string;
    delta: number;
    balance_after: number;
    reason: string;
    event_id?: string | null;
    /**
     * principal_type of the token that made the change
     */
    operator_type: string;
    operator_id: string;
    created_at: string;
};

export type CreateOrgRequest = {
    name: string;
    contact?: string;
    event_credits: number;
    max_attendees: number;
};

export type AdjustCreditsRequest = {
    /**
     * Non-zero; negative removes credits
     */
    delta: number;
    reason: string;
};

export type SetMaxAttendeesRequest = {
    max_attendees: number;
};

export type OrgId = string;

export type Offset = number;

export type Limit = number;

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzErrors = {
    /**
     * Unexpected server error
     */
    500: Error;
    /**
     * Service or database unavailable
     */
    503: Healthz;
};

export type GetHealthzError = GetHealthzErrors[keyof GetHealthzErrors];

export type GetHealthzResponses = {
    /**
     * Service is healthy
     */
    200: Healthz;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiInfoResponses = {
    /**
     * Basic service info
     */
    200: ApiInfo;
};

export type GetApiInfoResponse = GetApiInfoResponses[keyof GetApiInfoResponses];

export type GetOpenApiYamlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.yaml';
};

export type GetOpenApiYamlResponses = {
    /**
     * OpenAPI YAML
     */
    200: string;
};

export type GetOpenApiYamlResponse = GetOpenApiYamlResponses[keyof GetOpenApiYamlResponses];

export type GetOpenApijsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenApijsonResponses = {
    /**
     * OpenAPI JSON
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenApijsonResponse = GetOpenApijsonResponses[keyof GetOpenApijsonResponses];

export type PlatformLoginData = {
    body: PlatformLoginRequest;
    path?: never;
    query?: never;
    url: '/api/platform/login';
};

export type PlatformLoginErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    429: Error;
};

export type PlatformLoginError = PlatformLoginErrors[keyof PlatformLoginErrors];

export type PlatformLoginResponses = {
    /**
     * Login succeeded; the token is shown once
     */
    200: SessionToken;
};

export type PlatformLoginResponse = PlatformLoginResponses[keyof PlatformLoginResponses];

export type PlatformLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/logout';
};

export type PlatformLogoutErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type PlatformLogoutError = PlatformLogoutErrors[keyof PlatformLogoutErrors];

export type PlatformLogoutResponses = {
    /**
     * Token revoked
     */
    204: void;
};

export type PlatformLogoutResponse = PlatformLogoutResponses[keyof PlatformLogoutResponses];

export type GetPlatformMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/platform/me';
};

export type GetPlatformMeErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type GetPlatformMeError = GetPlatformMeErrors[keyof GetPlatformMeErrors];

export type GetPlatformMeResponses = {
    /**
     * Current operator
     */
    200: PlatformMe;
};

export type GetPlatformMeResponse = GetPlatformMeResponses[keyof GetPlatformMeResponses];

export type ChangePlatformPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/platform/password';
};

export type ChangePlatformPasswordErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type ChangePlatformPasswordError = ChangePlatformPasswordErrors[keyof ChangePlatformPasswordErrors];

export type ChangePlatformPasswordResponses = {
    /**
     * Password changed; the new token is shown once
     */
    200: SessionToken;
};

export type ChangePlatformPasswordResponse = ChangePlatformPasswordResponses[keyof ChangePlatformPasswordResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/platform/orgs';
};

export type ListOrgsErrors = {
    /**
     * Business error
     */
    401: Error;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * One page of organizations
     */
    200: OrgPage;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type CreateOrgData = {
    body: CreateOrgRequest;
    path?: never;
    query?: never;
    url: '/api/platform/orgs';
};

export type CreateOrgErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
};

export type CreateOrgError = CreateOrgErrors[keyof CreateOrgErrors];

export type CreateOrgResponses = {
    /**
     * Organization opened
     */
    201: OrgSummary;
};

export type CreateOrgResponse = CreateOrgResponses[keyof CreateOrgResponses];

export type GetOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}';
};

export type GetOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * Organization detail
     */
    200: OrgDetail;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type DisableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/disable';
};

export type DisableOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type DisableOrgError = DisableOrgErrors[keyof DisableOrgErrors];

export type DisableOrgResponses = {
    /**
     * Organization is disabled
     */
    204: void;
};

export type DisableOrgResponse = DisableOrgResponses[keyof DisableOrgResponses];

export type EnableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/enable';
};

export type EnableOrgErrors = {
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type EnableOrgError = EnableOrgErrors[keyof EnableOrgErrors];

export type EnableOrgResponses = {
    /**
     * Organization is active
     */
    204: void;
};

export type EnableOrgResponse = EnableOrgResponses[keyof EnableOrgResponses];

export type AdjustOrgCreditsData = {
    body: AdjustCreditsRequest;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/credits';
};

export type AdjustOrgCreditsErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
    /**
     * Business error
     */
    409: Error;
};

export type AdjustOrgCreditsError = AdjustOrgCreditsErrors[keyof AdjustOrgCreditsErrors];

export type AdjustOrgCreditsResponses = {
    /**
     * The ledger entry written
     */
    200: LedgerEntry;
};

export type AdjustOrgCreditsResponse = AdjustOrgCreditsResponses[keyof AdjustOrgCreditsResponses];

export type SetOrgMaxAttendeesData = {
    body: SetMaxAttendeesRequest;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/api/platform/orgs/{orgId}/max-attendees';
};

export type SetOrgMaxAttendeesErrors = {
    /**
     * Business error
     */
    400: Error;
    /**
     * Business error
     */
    401: Error;
    /**
     * Business error
     */
    404: Error;
};

export type SetOrgMaxAttendeesError = SetOrgMaxAttendeesErrors[keyof SetOrgMaxAttendeesErrors];

export type SetOrgMaxAttendeesResponses = {
    /**
     * Limit updated
     */
    204: void;
};

export type SetOrgMaxAttendeesResponse = SetOrgMaxAttendeesResponses[keyof SetOrgMaxAttendeesResponses];
